# Generated by Django 5.2.6 on 2025-09-08 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_remove_sobremi_caracteristica1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
