# Generated by Django 5.2.6 on 2025-09-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobremi',
            name='caracteristica1',
        ),
        migrations.RemoveField(
            model_name='sobremi',
            name='caracteristica2',
        ),
        migrations.RemoveField(
            model_name='sobremi',
            name='caracteristica3',
        ),
        migrations.RemoveField(
            model_name='sobremi',
            name='caracteristica4',
        ),
        migrations.RemoveField(
            model_name='sobremi',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='sobremi',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
